### ISSUE TITLE
missing services.xml

### ISSUE THREAD

**Issue by mitelg** [synonymous1984/SynonymousPriceCalculator#1]
Hi @synonymous1984 
looks good, but you forgot the services.xml to decorate the core service. the method in your "bootstrap" file should not work like this. see https://github.com/synonymous1984/SynonymousPriceCalculator/pull/2
greetings 
Michael Telgmann

**Comment by synonymous1984** [comment]
Hi Michael,

Yup, you´re right. I made this plugin from scratch cause I´m on holiday and have not dev-system at the moment :) I will add the services.xml to fix this... 👍

**Comment by synonymous1984** [comment]
Ok, I´ve merged your commit Michael - thanks for that...

**Comment by mitelg** [comment]
You're welcome! we always like to see community members, who want to help others with examples like this one :blush: :+1:

**Comment by synonymous1984** [comment]
Hi....

Jetzt auf deutsch :) Ihr könnt das Beispiel natürlich auch gerne in der
Doku zu den 5.2 Plugins am Ende verlinken wenn Ihr möchtet - dort gibt es
ja bereits eines von Shyim.

Ich bin von 23.-24. September bei Euch und freue mich schon Euch
kennenzulernen.

Liebe Grüße


2016-08-25 17:25 GMT+02:00 Michael Telgmann <notifications@github.com>:
