### ISSUE TITLE
non-existent service "shopware_storefront.price_calculation_service.inner"

### ISSUE THREAD

**Issue by larsbo** [synonymous1984/SynonymousPriceCalculator#3]
Trying to run the plugin on shopware 5.2.6 produces this error:

`Fatal error: Uncaught Symfony\Component\DependencyInjection\Exception\ServiceNotFoundException: The service "shopware_storefront.price_calculation_service" has a dependency on a non-existent service "shopware_storefront.price_calculation_service.inner"`

**Comment by synonymous1984** [comment]
Right, the correct argument in services.xml has to be
`<argument type="service" id="synonymous_price_calculator.price_calulation_service_decorator.inner"/>`

If updated the demo plugin - download and try again please.
